In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [2]:
data = pd.read_csv(r"/home/vatsal/Downloads/Churn_Modelling.csv")

In [3]:
data.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [4]:
data.describe()

,RowNumber,CustomerId,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
count,10000.00000,1.000000e+04,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.00000,10000.000000,10000.000000,10000.000000
mean,5000.50000,1.569094e+07,650.528800,38.921800,5.012800,76485.889288,1.530200,0.70550,0.515100,100090.239881,0.203700
std,2886.89568,7.193619e+04,96.653299,10.487806,2.892174,62397.405202,0.581654,0.45584,0.499797,57510.492818,0.402769
min,1.00000,1.556570e+07,350.000000,18.000000,0.000000,0.000000,1.000000,0.00000,0.000000,11.580000,0.000000
25%,2500.75000,1.562853e+07,584.000000,32.000000,3.000000,0.000000,1.000000,0.00000,0.000000,51002.110000,0.000000
50%,5000.50000,1.569074e+07,652.000000,37.000000,5.000000,97198.540000,1.000000,1.00000,1.000000,100193.915000,0.000000
75%,7500.25000,1.575323e+07,718.000000,44.000000,7.000000,127644.240000,2.000000,1.00000,1.000000,149388.247500,0.000000
max,10000.00000,1.581569e+07,850.000000,92.000000,10.000000,250898.090000,4.000000,1.00000,1.000000,199992.480000,1.000000

In [5]:
data['Geography'].value_counts()

France     5014
Germany    2509
Spain      2477
Name: Geography, dtype: int64

In [6]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
RowNumber          10000 non-null int64
CustomerId         10000 non-null int64
Surname            10000 non-null object
CreditScore        10000 non-null int64
Geography          10000 non-null object
Gender             10000 non-null object
Age                10000 non-null int64
Tenure             10000 non-null int64
Balance            10000 non-null float64
NumOfProducts      10000 non-null int64
HasCrCard          10000 non-null int64
IsActiveMember     10000 non-null int64
EstimatedSalary    10000 non-null float64
Exited             10000 non-null int64
dtypes: float64(2), int64(9), object(3)
memory usage: 1.1+ MB

In [7]:
data = data.drop(['RowNumber','CustomerId','Surname'],axis=1)

In [8]:
data.head(2)

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0

In [9]:
data = pd.get_dummies(columns=['Geography'],data=data)

In [10]:
data = pd.get_dummies(columns=['Gender'],data=data,drop_first=True)

In [11]:
data.head(2)

,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_France,Geography_Germany,Geography_Spain,Gender_Male
0,619,42,2,0.00,1,1,1,101348.88,1,1,0,0,0
1,608,41,1,83807.86,1,0,1,112542.58,0,0,0,1,0

In [12]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(data.drop(['Exited'],axis=1),data.Exited,test_size=0.2)

In [13]:
from sklearn.preprocessing import StandardScaler
ss = StandardScaler()

In [14]:
scaled_x_train = ss.fit_transform(x_train)
scaled_x_test = ss.transform(x_test)

In [15]:
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import Dropout

Using TensorFlow backend.

In [40]:
myclf = Sequential()

In [52]:
myclf.add(Dense(activation='relu',output_dim=6,input_dim=12))
myclf.add(Dense(activation='relu',output_dim=6))
myclf.add(Dense(activation='sigmoid',output_dim=1))
myclf.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])

/home/vatsal/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", input_dim=12, units=6)`
  """Entry point for launching an IPython kernel.
/home/vatsal/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:2: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", units=6)`

/home/vatsal/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:3: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="sigmoid", units=1)`
  This is separate from the ipykernel package so we can avoid doing imports until

In [16]:
from keras.wrappers.scikit_learn import KerasClassifier
from sklearn.model_selection import cross_val_score

In [25]:
def build_func():
    myclf = Sequential()
    myclf.add(Dense(activation='relu',output_dim=12,input_dim=12))
    myclf.add(Dropout(0.1))
    myclf.add(Dense(activation='relu',output_dim=12))
    myclf.add(Dropout(0.1))
    myclf.add(Dense(activation='sigmoid',output_dim=1))
    myclf.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])
    return myclf

In [33]:
kclf = KerasClassifier(build_fn=build_func,batch_size=32,epochs=100)

In [27]:
accuracy = cross_val_score(estimator=kclf,cv=10,n_jobs=-1,X=scaled_x_train,y=y_train)

/home/vatsal/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:3: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", input_dim=12, units=12)`
  This is separate from the ipykernel package so we can avoid doing imports until
/home/vatsal/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:3: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", input_dim=12, units=12)`
  This is separate from the ipykernel package so we can avoid doing imports until
/home/vatsal/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:3: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", input_dim=12, units=12)`
  This is separate from the ipykernel package so we can avoid doing imports until
/home/vatsal/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:3: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", input_dim=12, units=12)`
  This is separate from the ipykernel package so we can avoid doing imports until
/home/vatsal/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:5: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", units=12)`
  """
/home/vatsal/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:5: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", units=12)`
  """
/home/vatsal/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:5: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", units=12)`
  """
/home/vatsal/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:7: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="sigmoid", units=1)`
  import sys
/home/vatsal/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:5: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", units=12)`
  """
/home/vatsal/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:7: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="sigmoid", units=1)`
  import sys
/home/vatsal/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:7: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="sigmoid", units=1)`
  import sys
/home/vatsal/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:7: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="sigmoid", units=1)`
  import sys

Epoch 1/10
  32/7200 [..............................] - ETA: 43s - loss: 1.0555 - acc: 0.1562Epoch 1/10
 576/7200 [=>............................] - ETA: 3s - loss: 0.9719 - acc: 0.2569Epoch 1/10
Epoch 1/10
7200/7200 [==============================] - 2s - loss: 0.6628 - acc: 0.6158
6944/7200 [===========================>..] - ETA: 0s - loss: 0.6626 - acc: 0.6161Epoch 2/10
 608/7200 [=>............................] - ETA: 1s - loss: 0.5135 - acc: 0.7862
Epoch 2/10
7200/7200 [==============================] - 2s - loss: 0.6593 - acc: 0.6214
 800/7200 [==>...........................] - ETA: 1s - loss: 0.5171 - acc: 0.7800Epoch 2/10
7200/7200 [==============================] - 2s - loss: 0.6590 - acc: 0.6208
Epoch 2/10
7200/7200 [==============================] - 1s - loss: 0.4930 - acc: 0.7908
Epoch 3/10
  32/7200 [..............................] - ETA: 1s - loss: 0.5101 - acc: 0.7812
Epoch 3/10
1088/7200 [===>..........................] - ETA: 1s - loss: 0.4615 - acc: 0.8088
Epoch 3/10
7200/7200 [==============================] - 2s - loss: 0.4877 - acc: 0.7954
1216/7200 [====>.........................] - ETA: 2s - loss: 0.4790 - acc: 0.7977Epoch 3/10
5248/7200 [====================>.........] - ETA: 0s - loss: 0.4598 - acc: 0.8037
Epoch 4/10
6496/7200 [==========================>...] - ETA: 0s - loss: 0.4616 - acc: 0.8022
6400/7200 [=========================>....] - ETA: 0s - loss: 0.4631 - acc: 0.7995Epoch 4/10
7200/7200 [==============================] - 1s - loss: 0.4596 - acc: 0.8040
7168/7200 [============================>.] - ETA: 0s - loss: 0.4581 - acc: 0.8025Epoch 4/10
7200/7200 [==============================] - 2s - loss: 0.4575 - acc: 0.8028     Epoch 4/10

7200/7200 [==============================] - 2s - loss: 0.4433 - acc: 0.8071
7200/7200 [==============================] - 1s - loss: 0.4404 - acc: 0.8094     Epoch 5/10

Epoch 5/10
7200/7200 [==============================] - 2s - loss: 0.4427 - acc: 0.8065
1504/7200 [=====>........................] - ETA: 1s - loss: 0.4354 - acc: 0.8078Epoch 5/10

  32/7200 [..............................] - ETA: 1s - loss: 0.4026 - acc: 0.8438Epoch 5/10
5248/7200 [====================>.........] - ETA: 0s - loss: 0.4244 - acc: 0.8136
5056/7200 [====================>.........] - ETA: 0s - loss: 0.4171 - acc: 0.8190Epoch 6/10
6080/7200 [========================>.....] - ETA: 0s - loss: 0.4250 - acc: 0.8133
 352/7200 [>.............................] - ETA: 2s - loss: 0.4693 - acc: 0.7926Epoch 6/10
7200/7200 [==============================] - 2s - loss: 0.4264 - acc: 0.8128
Epoch 6/10
7200/7200 [==============================] - 2s - loss: 0.4183 - acc: 0.8196
Epoch 6/10
5760/7200 [=======================>......] - ETA: 0s - loss: 0.4102 - acc: 0.8262
Epoch 7/10
7200/7200 [==============================] - 2s - loss: 0.4163 - acc: 0.8235
Epoch 7/10
7200/7200 [==============================] - 1s - loss: 0.4100 - acc: 0.8268
Epoch 7/10
2144/7200 [=======>......................] - ETA: 1s - loss: 0.4097 - acc: 0.8246
Epoch 7/10
5728/7200 [======================>.......] - ETA: 0s - loss: 0.4016 - acc: 0.8321
5120/7200 [====================>.........] - ETA: 0s - loss: 0.4131 - acc: 0.8221Epoch 8/10
7200/7200 [==============================] - 2s - loss: 0.4035 - acc: 0.8303
5888/7200 [=======================>......] - ETA: 0s - loss: 0.4113 - acc: 0.8247Epoch 8/10
1408/7200 [====>.........................] - ETA: 1s - loss: 0.3879 - acc: 0.8459
6944/7200 [===========================>..] - ETA: 0s - loss: 0.4072 - acc: 0.8269Epoch 8/10
 832/7200 [==>...........................] - ETA: 2s - loss: 0.3839 - acc: 0.8594
Epoch 8/10
5248/7200 [====================>.........] - ETA: 0s - loss: 0.3931 - acc: 0.8384
Epoch 9/10
7200/7200 [==============================] - 1s - loss: 0.3985 - acc: 0.8346
 832/7200 [==>...........................] - ETA: 1s - loss: 0.3876 - acc: 0.8377Epoch 9/10
7200/7200 [==============================] - 2s - loss: 0.3924 - acc: 0.8378
Epoch 9/10
1504/7200 [=====>........................] - ETA: 1s - loss: 0.3812 - acc: 0.8378
  32/7200 [..............................] - ETA: 2s - loss: 0.3183 - acc: 0.8750Epoch 9/10
7200/7200 [==============================] - 1s - loss: 0.3897 - acc: 0.8368

5536/7200 [======================>.......] - ETA: 0s - loss: 0.3922 - acc: 0.8354Epoch 10/10
Epoch 10/10
6048/7200 [========================>.....] - ETA: 0s - loss: 0.3804 - acc: 0.8419
2624/7200 [=========>....................] - ETA: 1s - loss: 0.3917 - acc: 0.8323Epoch 10/10
4512/7200 [=================>............] - ETA: 0s - loss: 0.3799 - acc: 0.8406
Epoch 10/10
7200/7200 [==============================] - 1s - loss: 0.3846 - acc: 0.8401
4000/7200 [===============>..............] - ETA: 0s - loss: 0.3711 - acc: 0.8452
7200/7200 [==============================] - 1s - loss: 0.3852 - acc: 0.8389
7200/7200 [==============================] - 1s - loss: 0.3762 - acc: 0.8449
608/800 [=====================>........] - ETA: 0sEpoch 1/10
Epoch 1/10
 928/7200 [==>...........................] - ETA: 3s - loss: 1.0456 - acc: 0.2392Epoch 1/10
Epoch 1/10
4896/7200 [===================>..........] - ETA: 0s - loss: 0.7479 - acc: 0.5247
Epoch 2/10
 224/7200 [..............................] - ETA: 1s - loss: 0.4984 - acc: 0.8080
Epoch 2/10
2112/7200 [=======>......................] - ETA: 1s - loss: 0.5029 - acc: 0.7884
6720/7200 [===========================>..] - ETA: 0s - loss: 0.6878 - acc: 0.6012Epoch 2/10
7200/7200 [==============================] - 2s - loss: 0.6758 - acc: 0.6151
2400/7200 [=========>....................] - ETA: 1s - loss: 0.4941 - acc: 0.7921Epoch 2/10
7200/7200 [==============================] - 2s - loss: 0.4775 - acc: 0.7989
6976/7200 [============================>.] - ETA: 0s - loss: 0.4819 - acc: 0.7937Epoch 3/10
7104/7200 [============================>.] - ETA: 0s - loss: 0.4807 - acc: 0.7945
Epoch 3/10
5952/7200 [=======================>......] - ETA: 0s - loss: 0.4871 - acc: 0.7949
Epoch 3/10
1920/7200 [=======>......................] - ETA: 1s - loss: 0.4688 - acc: 0.8042
Epoch 3/10
7200/7200 [==============================] - 1s - loss: 0.4459 - acc: 0.8136
Epoch 4/10
 576/7200 [=>............................] - ETA: 1s - loss: 0.4488 - acc: 0.8073
Epoch 4/10
 416/7200 [>.............................] - ETA: 1s - loss: 0.4149 - acc: 0.8245
Epoch 4/10
2592/7200 [=========>....................] - ETA: 0s - loss: 0.4215 - acc: 0.8183
Epoch 4/10
7200/7200 [==============================] - 1s - loss: 0.4275 - acc: 0.8140
Epoch 5/10
7200/7200 [==============================] - 1s - loss: 0.4274 - acc: 0.8157     Epoch 5/10

6336/7200 [=========================>....] - ETA: 0s - loss: 0.4313 - acc: 0.8149
1760/7200 [======>.......................] - ETA: 1s - loss: 0.4119 - acc: 0.8233Epoch 5/10
7200/7200 [==============================] - 2s - loss: 0.4311 - acc: 0.8150
1600/7200 [=====>........................] - ETA: 1s - loss: 0.4117 - acc: 0.8206Epoch 5/10
7200/7200 [==============================] - 1s - loss: 0.4151 - acc: 0.8225
Epoch 6/10
7200/7200 [==============================] - 2s - loss: 0.4127 - acc: 0.8222
Epoch 6/10
7200/7200 [==============================] - 1s - loss: 0.4159 - acc: 0.8197
Epoch 6/10
 832/7200 [==>...........................] - ETA: 2s - loss: 0.4340 - acc: 0.8077
Epoch 6/10
4416/7200 [=================>............] - ETA: 1s - loss: 0.4101 - acc: 0.8245
Epoch 7/10
7200/7200 [==============================] - 1s - loss: 0.4086 - acc: 0.8292
5056/7200 [====================>.........] - ETA: 0s - loss: 0.4073 - acc: 0.8271Epoch 7/10
 832/7200 [==>...........................] - ETA: 3s - loss: 0.4009 - acc: 0.8293
Epoch 7/10
7200/7200 [==============================] - 2s - loss: 0.4070 - acc: 0.8313
1632/7200 [=====>........................] - ETA: 1s - loss: 0.4001 - acc: 0.8309Epoch 7/10
6848/7200 [===========================>..] - ETA: 0s - loss: 0.3979 - acc: 0.8328
Epoch 8/10
5376/7200 [=====================>........] - ETA: 0s - loss: 0.3980 - acc: 0.8371
Epoch 8/10

 736/7200 [==>...........................] - ETA: 2s - loss: 0.3992 - acc: 0.8329
Epoch 8/10
1536/7200 [=====>........................] - ETA: 1s - loss: 0.4006 - acc: 0.8359
Epoch 8/10
7200/7200 [==============================] - 1s - loss: 0.3901 - acc: 0.8400
5792/7200 [=======================>......] - ETA: 0s - loss: 0.3927 - acc: 0.8420Epoch 9/10
 288/7200 [>.............................] - ETA: 1s - loss: 0.4256 - acc: 0.8125
Epoch 9/10
6272/7200 [=========================>....] - ETA: 0s - loss: 0.3860 - acc: 0.8439
Epoch 9/10
7200/7200 [==============================] - 2s - loss: 0.3860 - acc: 0.8428
 928/7200 [==>...........................] - ETA: 1s - loss: 0.3972 - acc: 0.8405Epoch 9/10
7200/7200 [==============================] - 2s - loss: 0.3889 - acc: 0.8364
4416/7200 [=================>............] - ETA: 0s - loss: 0.3892 - acc: 0.8345Epoch 10/10
5344/7200 [=====================>........] - ETA: 0s - loss: 0.3851 - acc: 0.8374
Epoch 10/10
1696/7200 [======>.......................] - ETA: 1s - loss: 0.3798 - acc: 0.8320
Epoch 10/10
7200/7200 [==============================] - 2s - loss: 0.3865 - acc: 0.8394
1824/7200 [======>.......................] - ETA: 1s - loss: 0.3858 - acc: 0.8361Epoch 10/10
6432/7200 [=========================>....] - ETA: 0s - loss: 0.3848 - acc: 0.8408
7200/7200 [==============================] - 2s - loss: 0.3815 - acc: 0.8418
7200/7200 [==============================] - 2s - loss: 0.3785 - acc: 0.8444
7200/7200 [==============================] - 2s - loss: 0.3851 - acc: 0.8428
512/800 [==================>...........] - ETA: 0sEpoch 1/10
Epoch 1/10
7200/7200 [==============================] - 1s - loss: 0.5045 - acc: 0.7858
Epoch 2/10
7200/7200 [==============================] - 1s - loss: 0.5033 - acc: 0.7860
 320/7200 [>.............................] - ETA: 1s - loss: 0.4927 - acc: 0.7750Epoch 2/10
7200/7200 [==============================] - 1s - loss: 0.4534 - acc: 0.7967
Epoch 3/10
  32/7200 [..............................] - ETA: 1s - loss: 0.4032 - acc: 0.8125
Epoch 3/10
7200/7200 [==============================] - 1s - loss: 0.4396 - acc: 0.8006
Epoch 4/10
7200/7200 [==============================] - 1s - loss: 0.4428 - acc: 0.7974
Epoch 4/10
7200/7200 [==============================] - 1s - loss: 0.4308 - acc: 0.8125
Epoch 5/10
7200/7200 [==============================] - 1s - loss: 0.4333 - acc: 0.8111
Epoch 5/10
7200/7200 [==============================] - 1s - loss: 0.4229 - acc: 0.8124
Epoch 6/10
7200/7200 [==============================] - 1s - loss: 0.4229 - acc: 0.8161
Epoch 6/10
7072/7200 [============================>.] - ETA: 0s - loss: 0.4046 - acc: 0.8272
Epoch 7/10
7200/7200 [==============================] - 1s - loss: 0.4052 - acc: 0.8268
Epoch 7/10
7200/7200 [==============================] - 1s - loss: 0.3981 - acc: 0.8318
Epoch 8/10
7200/7200 [==============================] - 1s - loss: 0.3955 - acc: 0.8308
Epoch 8/10
7200/7200 [==============================] - 1s - loss: 0.3897 - acc: 0.8382
Epoch 9/10
7200/7200 [==============================] - 1s - loss: 0.3866 - acc: 0.8413
Epoch 9/10
7200/7200 [==============================] - 1s - loss: 0.3832 - acc: 0.8428
Epoch 10/10
7200/7200 [==============================] - 1s - loss: 0.3817 - acc: 0.8444
Epoch 10/10
7200/7200 [==============================] - 1s - loss: 0.3791 - acc: 0.8418
7200/7200 [==============================] - 1s - loss: 0.3782 - acc: 0.8433
 32/800 [>.............................] - ETA: 1s

In [28]:
print(accuracy.mean())
print(accuracy.std())

0.8495
0.0178902906628

In [29]:
accuracy

array([ 0.82   ,  0.87875,  0.8525 ,  0.835  ,  0.88   ,  0.835  ,
        0.845  ,  0.8575 ,  0.845  ,  0.84625])

In [34]:
kclf.fit(scaled_x_train,y_train)

/home/vatsal/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:3: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", input_dim=12, units=12)`
  This is separate from the ipykernel package so we can avoid doing imports until
/home/vatsal/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:5: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", units=12)`
  """
/home/vatsal/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:7: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="sigmoid", units=1)`
  import sys

Epoch 1/100
8000/8000 [==============================] - 0s - loss: 0.5520 - acc: 0.7734
Epoch 2/100
8000/8000 [==============================] - 0s - loss: 0.4586 - acc: 0.8066
Epoch 3/100
8000/8000 [==============================] - 0s - loss: 0.4356 - acc: 0.8120
Epoch 4/100
8000/8000 [==============================] - 0s - loss: 0.4259 - acc: 0.8136
Epoch 5/100
8000/8000 [==============================] - 0s - loss: 0.4190 - acc: 0.8201
Epoch 6/100
8000/8000 [==============================] - 0s - loss: 0.4130 - acc: 0.8183
Epoch 7/100
8000/8000 [==============================] - 0s - loss: 0.4127 - acc: 0.8197
Epoch 8/100
8000/8000 [==============================] - 0s - loss: 0.4001 - acc: 0.8265
Epoch 9/100
8000/8000 [==============================] - 0s - loss: 0.3944 - acc: 0.8301
Epoch 10/100
8000/8000 [==============================] - 0s - loss: 0.3854 - acc: 0.8373
Epoch 11/100
8000/8000 [==============================] - 0s - loss: 0.3786 - acc: 0.8421
Epoch 12/100
8000/8000 [==============================] - 0s - loss: 0.3764 - acc: 0.8449
Epoch 13/100
8000/8000 [==============================] - 0s - loss: 0.3759 - acc: 0.8419
Epoch 14/100
8000/8000 [==============================] - 0s - loss: 0.3688 - acc: 0.8479
Epoch 15/100
8000/8000 [==============================] - 0s - loss: 0.3679 - acc: 0.8450
Epoch 16/100
8000/8000 [==============================] - 0s - loss: 0.3684 - acc: 0.8480
Epoch 17/100
8000/8000 [==============================] - 0s - loss: 0.3666 - acc: 0.8452
Epoch 18/100
8000/8000 [==============================] - 0s - loss: 0.3644 - acc: 0.8500
Epoch 19/100
8000/8000 [==============================] - 0s - loss: 0.3651 - acc: 0.8471
Epoch 20/100
8000/8000 [==============================] - 0s - loss: 0.3620 - acc: 0.8498
Epoch 21/100
8000/8000 [==============================] - 0s - loss: 0.3589 - acc: 0.8494
Epoch 22/100
8000/8000 [==============================] - 0s - loss: 0.3602 - acc: 0.8486
Epoch 23/100
8000/8000 [==============================] - 0s - loss: 0.3582 - acc: 0.8515
Epoch 24/100
8000/8000 [==============================] - 0s - loss: 0.3619 - acc: 0.8491
Epoch 25/100
8000/8000 [==============================] - 0s - loss: 0.3580 - acc: 0.8526
Epoch 26/100
8000/8000 [==============================] - 0s - loss: 0.3558 - acc: 0.8519
Epoch 27/100
8000/8000 [==============================] - 0s - loss: 0.3568 - acc: 0.8521
Epoch 28/100
8000/8000 [==============================] - 0s - loss: 0.3578 - acc: 0.8527
Epoch 29/100
8000/8000 [==============================] - 0s - loss: 0.3588 - acc: 0.8543
Epoch 30/100
8000/8000 [==============================] - 0s - loss: 0.3573 - acc: 0.8562
Epoch 31/100
8000/8000 [==============================] - 0s - loss: 0.3550 - acc: 0.8536
Epoch 32/100
8000/8000 [==============================] - 0s - loss: 0.3546 - acc: 0.8531
Epoch 33/100
8000/8000 [==============================] - 0s - loss: 0.3592 - acc: 0.8544
Epoch 34/100
8000/8000 [==============================] - 0s - loss: 0.3536 - acc: 0.8539
Epoch 35/100
8000/8000 [==============================] - 0s - loss: 0.3536 - acc: 0.8558
Epoch 36/100
8000/8000 [==============================] - 0s - loss: 0.3553 - acc: 0.8564
Epoch 37/100
8000/8000 [==============================] - 0s - loss: 0.3525 - acc: 0.8558
Epoch 38/100
8000/8000 [==============================] - 0s - loss: 0.3525 - acc: 0.8592
Epoch 39/100
8000/8000 [==============================] - 0s - loss: 0.3513 - acc: 0.8569
Epoch 40/100
8000/8000 [==============================] - 0s - loss: 0.3489 - acc: 0.8569
Epoch 41/100
8000/8000 [==============================] - 0s - loss: 0.3539 - acc: 0.8558
Epoch 42/100
8000/8000 [==============================] - 0s - loss: 0.3523 - acc: 0.8564
Epoch 43/100
8000/8000 [==============================] - 0s - loss: 0.3504 - acc: 0.8564
Epoch 44/100
8000/8000 [==============================] - 0s - loss: 0.3474 - acc: 0.8596
Epoch 45/100
8000/8000 [==============================] - 0s - loss: 0.3529 - acc: 0.8553
Epoch 46/100
8000/8000 [==============================] - 0s - loss: 0.3501 - acc: 0.8570
Epoch 47/100
8000/8000 [==============================] - 0s - loss: 0.3499 - acc: 0.8580
Epoch 48/100
8000/8000 [==============================] - 0s - loss: 0.3502 - acc: 0.8558
Epoch 49/100
8000/8000 [==============================] - 0s - loss: 0.3494 - acc: 0.8591
Epoch 50/100
8000/8000 [==============================] - 0s - loss: 0.3471 - acc: 0.8561
Epoch 51/100
8000/8000 [==============================] - 0s - loss: 0.3462 - acc: 0.8606
Epoch 52/100
8000/8000 [==============================] - 0s - loss: 0.3470 - acc: 0.8604
Epoch 53/100
8000/8000 [==============================] - 0s - loss: 0.3472 - acc: 0.8605
Epoch 54/100
8000/8000 [==============================] - 0s - loss: 0.3475 - acc: 0.8603
Epoch 55/100
8000/8000 [==============================] - 0s - loss: 0.3483 - acc: 0.8576
Epoch 56/100
8000/8000 [==============================] - 0s - loss: 0.3444 - acc: 0.8592
Epoch 57/100
8000/8000 [==============================] - 0s - loss: 0.3481 - acc: 0.8591
Epoch 58/100
8000/8000 [==============================] - 0s - loss: 0.3487 - acc: 0.8601
Epoch 59/100
8000/8000 [==============================] - 0s - loss: 0.3445 - acc: 0.8574
Epoch 60/100
8000/8000 [==============================] - 0s - loss: 0.3449 - acc: 0.8584
Epoch 61/100
8000/8000 [==============================] - 0s - loss: 0.3469 - acc: 0.8580
Epoch 62/100
8000/8000 [==============================] - 0s - loss: 0.3446 - acc: 0.8616
Epoch 63/100
8000/8000 [==============================] - 0s - loss: 0.3458 - acc: 0.8605
Epoch 64/100
8000/8000 [==============================] - 0s - loss: 0.3449 - acc: 0.8609
Epoch 65/100
8000/8000 [==============================] - 0s - loss: 0.3442 - acc: 0.8616
Epoch 66/100
8000/8000 [==============================] - 0s - loss: 0.3455 - acc: 0.8596
Epoch 67/100
8000/8000 [==============================] - 0s - loss: 0.3475 - acc: 0.8622
Epoch 68/100
8000/8000 [==============================] - 0s - loss: 0.3433 - acc: 0.8608
Epoch 69/100
8000/8000 [==============================] - 0s - loss: 0.3442 - acc: 0.8613
Epoch 70/100
8000/8000 [==============================] - 0s - loss: 0.3418 - acc: 0.8628
Epoch 71/100
8000/8000 [==============================] - 0s - loss: 0.3421 - acc: 0.8598
Epoch 72/100
8000/8000 [==============================] - 0s - loss: 0.3452 - acc: 0.8585
Epoch 73/100
8000/8000 [==============================] - 0s - loss: 0.3454 - acc: 0.8600
Epoch 74/100
8000/8000 [==============================] - 0s - loss: 0.3434 - acc: 0.8594
Epoch 75/100
8000/8000 [==============================] - 0s - loss: 0.3455 - acc: 0.8601
Epoch 76/100
8000/8000 [==============================] - 0s - loss: 0.3426 - acc: 0.8608
Epoch 77/100
8000/8000 [==============================] - 0s - loss: 0.3477 - acc: 0.8591
Epoch 78/100
8000/8000 [==============================] - 0s - loss: 0.3443 - acc: 0.8592
Epoch 79/100
8000/8000 [==============================] - 0s - loss: 0.3435 - acc: 0.8613
Epoch 80/100
8000/8000 [==============================] - 0s - loss: 0.3403 - acc: 0.8613
Epoch 81/100
8000/8000 [==============================] - 0s - loss: 0.3428 - acc: 0.8621
Epoch 82/100
8000/8000 [==============================] - 0s - loss: 0.3386 - acc: 0.8621
Epoch 83/100
8000/8000 [==============================] - 0s - loss: 0.3448 - acc: 0.8611
Epoch 84/100
8000/8000 [==============================] - 0s - loss: 0.3443 - acc: 0.8587     - ETA: 0s - loss: 0.367
Epoch 85/100
8000/8000 [==============================] - 1s - loss: 0.3418 - acc: 0.8600
Epoch 86/100
8000/8000 [==============================] - 0s - loss: 0.3443 - acc: 0.8609
Epoch 87/100

8000/8000 [==============================] - 0s - loss: 0.3453 - acc: 0.8605
Epoch 88/100
8000/8000 [==============================] - 0s - loss: 0.3425 - acc: 0.8605
Epoch 89/100
8000/8000 [==============================] - 0s - loss: 0.3393 - acc: 0.8600
Epoch 90/100
8000/8000 [==============================] - 0s - loss: 0.3430 - acc: 0.8610
Epoch 91/100
8000/8000 [==============================] - 0s - loss: 0.3456 - acc: 0.8598
Epoch 92/100
8000/8000 [==============================] - 0s - loss: 0.3445 - acc: 0.8591
Epoch 93/100
8000/8000 [==============================] - 0s - loss: 0.3398 - acc: 0.8620
Epoch 94/100
8000/8000 [==============================] - 0s - loss: 0.3413 - acc: 0.8614
Epoch 95/100
8000/8000 [==============================] - 0s - loss: 0.3424 - acc: 0.8610
Epoch 96/100
8000/8000 [==============================] - 0s - loss: 0.3390 - acc: 0.8630
Epoch 97/100
8000/8000 [==============================] - 0s - loss: 0.3432 - acc: 0.8599
Epoch 98/100
8000/8000 [==============================] - 0s - loss: 0.3434 - acc: 0.8614
Epoch 99/100
8000/8000 [==============================] - 0s - loss: 0.3414 - acc: 0.8618
Epoch 100/100
8000/8000 [==============================] - 0s - loss: 0.3407 - acc: 0.8599

In [35]:
yp = kclf.predict(scaled_x_test)

1760/2000 [=========================>....] - ETA: 0s

In [39]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test,yp)

array([[1532,   51],
       [ 220,  197]])